# Generated by Django 4.2.6 on 2023-11-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_marca_modelo_camion_airbags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicaSeguridad',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('luces_testigos', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('airbags', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escaner',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('sistema_abs', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('ecu_transmision', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('ecu_airbag', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorCamion',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('puertas', models.BooleanField(default=False)),
                ('espejos', models.BooleanField(default=False)),
                ('ventanas', models.BooleanField(default=False)),
                ('focos', models.BooleanField(default=False)),
                ('parachoques', models.BooleanField(default=False)),
                ('capot', models.BooleanField(default=False)),
                ('techo', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorCamion',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('tapiz', models.BooleanField(default=False)),
                ('asientos', models.BooleanField(default=False)),
                ('talero', models.BooleanField(default=False)),
                ('cerradura', models.BooleanField(default=False)),
                ('botones', models.BooleanField(default=False)),
                ('limpiaparabrisas', models.BooleanField(default=False)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Llantas',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('condicion_neumaticos', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('condicion_motor', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('ruido_motor', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('cableado', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('condicion_bateria', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('humo_visible', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('mangueras_motor', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('condicion_carter_aceite', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('sistema_refrigeracion', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('condicion_transmision', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionFrenos',
            fields=[
                ('camion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.camion')),
                ('direccion_funcionamiento', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('amortiguadores_condicion', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('frenos_estado', models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='camion',
            name='airbags',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='amortiguadores_condicion',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='asientos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='botones',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='cableado',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='capot',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='cerradura',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_electronica_seguridad',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_escaner',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_exterior',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_interior',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_motor',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_neumaticos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='comentarios_suspension_freno',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='condicion_bateria',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='condicion_carter_aceite',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='condicion_motor',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='condicion_neumaticos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='condicion_transmision',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='direccion_funcionamiento',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ecu_airbag',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ecu_transmision',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='espejos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='focos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='frenos_estado',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='humo_visible',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='limpiaparabrisas',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='luces_testigos',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='mangueras_motor',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='parachoques',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='puertas',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ruido_motor',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='sistema_abs',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='sistema_refrigeracion',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='talero',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='tapiz',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='techo',
        ),
        migrations.RemoveField(
            model_name='camion',
            name='ventanas',
        ),
    ]
