# Generated by Django 4.2.6 on 2023-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_electronicaseguridad_escaner_exteriorcamion_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteriorcamion',
            name='capot',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='espejos',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='focos',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='parachoques',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='puertas',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='techo',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='exteriorcamion',
            name='ventanas',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='asientos',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='botones',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='cerradura',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='limpiaparabrisas',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='talero',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AlterField(
            model_name='interiorcamion',
            name='tapiz',
            field=models.CharField(choices=[('ok', 'Ok'), ('con_detalle', 'Con Detalle'), ('na', 'N/A')], default='na', max_length=20),
        ),
    ]
