# Generated by Django 4.2.6 on 2023-11-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_camion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='permiso_circulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='proxima_inspeccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='revision_tecnica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camion',
            name='soap',
            field=models.DateField(blank=True, null=True),
        ),
    ]
